/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.Login_DAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class CadVi_GUI extends javax.swing.JFrame {

    public static String url = "jdbc:mysql://localhost:3307/aprender"
        + "?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false";
  static String username = "root";        //nome de um usuário de seu BD
  static String password = "1234"; 
    public CadVi_GUI() {
        initComponents();
    }
     //inicio dos metodos
    
   
public static DefaultTableModel visitante(ResultSet rs) {
    try {
        Vector<String> colunas = new Vector<>();
        colunas.add("Código");
        colunas.add("Nome");
        colunas.add("Documento");
        colunas.add("Empresa");
        colunas.add("Motivo");
        colunas.add("Colaborador");

        Vector<Vector<Object>> linhas = new Vector<>();
        while (rs.next()) {
            Vector<Object> novaLinha = new Vector<>();
            novaLinha.add(rs.getInt("visitante_id"));
            novaLinha.add(rs.getString("cli_nome"));
            novaLinha.add(rs.getString("cli_documento"));
            novaLinha.add(rs.getString("cli_empresa"));
            novaLinha.add(rs.getString("cli_motivo_empresa"));
            novaLinha.add(rs.getString("cli_colaborador"));
            linhas.add(novaLinha);
        }
        return new DefaultTableModel(linhas, colunas);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao montar tabela: " + e.getMessage());
        return null;
    }
}


    
    
    
    
    
    
    
    // fim dos metodos


        
        // ----------Incio

       public void refresh() {
    try {
        Connection conn = DriverManager.getConnection(url, username, password);
        String sql = "SELECT * FROM visitante";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
         // chama o método novo
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao atualizar tabela: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        sair_btn = new javax.swing.JButton();
        home = new org.edisoncor.gui.panel.PanelImage();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cadastro_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        img2 = new org.edisoncor.gui.panel.PanelImage();
        col5_txt = new javax.swing.JTextField();
        nom5_txt = new javax.swing.JTextField();
        doc5_txt = new javax.swing.JTextField();
        emp5_txt = new javax.swing.JTextField();
        mot5_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 92, 143));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tech Solutions S.A");

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        sair_btn.setBackground(new java.awt.Color(255, 51, 51));
        sair_btn.setText("X");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/casa.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(sair_btn)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sair_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 730, 110);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel7.setText("CADASTRO DE VISITANTE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 110, 370, 38);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("RG:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 300, 140, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Empresa:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 340, 170, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Colaborador:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 420, 160, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Motivo da visita:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 380, 110, 17);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Nome completo:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 260, 110, 17);

        cadastro_btn.setBackground(new java.awt.Color(153, 153, 153));
        cadastro_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cadastro_btn.setText("Cadastrar novo visitante");
        cadastro_btn.setBorder(new javax.swing.border.MatteBorder(null));
        cadastro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cadastro_btn);
        cadastro_btn.setBounds(390, 500, 160, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Novo Visitante");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 180, 120, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Essa tela permite adicionar novos visitantes ao sistema");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 210, 350, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Foto:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 260, 34, 14);

        btnFoto.setText("Procurar");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoto);
        btnFoto.setBounds(570, 370, 90, 25);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("Limpar");
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 500, 75, 30);

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/camera.png"))); // NOI18N

        javax.swing.GroupLayout img2Layout = new javax.swing.GroupLayout(img2);
        img2.setLayout(img2Layout);
        img2Layout.setHorizontalGroup(
            img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        img2Layout.setVerticalGroup(
            img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(img2);
        img2.setBounds(570, 250, 100, 100);
        jPanel1.add(col5_txt);
        col5_txt.setBounds(150, 410, 320, 30);
        jPanel1.add(nom5_txt);
        nom5_txt.setBounds(150, 250, 320, 30);
        jPanel1.add(doc5_txt);
        doc5_txt.setBounds(150, 290, 320, 30);
        jPanel1.add(emp5_txt);
        emp5_txt.setBounds(150, 330, 320, 30);
        jPanel1.add(mot5_txt);
        mot5_txt.setBounds(150, 370, 320, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 560);

        setSize(new java.awt.Dimension(732, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        Controller.Imagem_DAO.abrirFoto(img2);
    }//GEN-LAST:event_btnFotoActionPerformed

    private void cadastro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_btnActionPerformed
        Controller.Visitante_DAO.cadastrar();
    }//GEN-LAST:event_cadastro_btnActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        new Menu_GUI(Login_DAO.tipoUsuarioLogado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadVi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadVi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadVi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadVi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadVi_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton cadastro_btn;
    public static javax.swing.JTextField col5_txt;
    public static javax.swing.JTextField doc5_txt;
    public static javax.swing.JTextField emp5_txt;
    private org.edisoncor.gui.panel.PanelImage home;
    private org.edisoncor.gui.panel.PanelImage img2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField mot5_txt;
    public static javax.swing.JTextField nom5_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private javax.swing.JButton sair_btn;
    // End of variables declaration//GEN-END:variables
}
