/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Login_DAO;
import static View.CadVi_GUI.url;
import static View.CadVi_GUI.username;
import static View.Consult_GUI.url;
import static View.Consult_GUI.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class ConsultaEst_GUI extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaEst_GUI
     */
    public static String url = "jdbc:mysql://localhost:3306/aprender"
        + "?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false";
  static String username = "root";        //nome de um usuário de seu BD
  static String password = ""; 
    public ConsultaEst_GUI() {
        initComponents();
        refresh();
    }
    
    public static DefaultTableModel carros(ResultSet rs) {
    try {
        Vector<String> colunas = new Vector<>();
        colunas.add("Codigo");
        colunas.add("Placa");
        colunas.add("Modelo");
        colunas.add("Cor");
        colunas.add("Tipo");
        colunas.add("Numero");
        

        Vector<Vector<Object>> linhas = new Vector<>();
        while (rs.next()) {
            Vector<Object> novaLinha = new Vector<>();
            novaLinha.add(rs.getInt("carro_id"));
            novaLinha.add(rs.getString("cli_placa"));
            novaLinha.add(rs.getString("cli_modelo"));
            novaLinha.add(rs.getString("cli_cor"));
            novaLinha.add(rs.getString("cli_tipo"));
            novaLinha.add(rs.getString("cli_numero"));
            linhas.add(novaLinha);
        }
        return new DefaultTableModel(linhas, colunas);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao montar tabela: " + e.getMessage());
        return null;
    }
}


    
    
    
    
    
    
    
    // fim dos metodos


        
        // ----------Incio

       public void refresh() {
    try {
        Connection conn = DriverManager.getConnection(url, username, password);
        String sql = "SELECT * FROM carros";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        tabela1.setModel(carros(rs));
         // chama o método novo
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao atualizar tabela: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("aprender?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        funcQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Func f");
        funcList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : funcQuery.getResultList();
        carrosQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Carros c");
        carrosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carrosQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        sair_btn2 = new javax.swing.JButton();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cod8_txt = new javax.swing.JTextField();
        pesquisar = new org.edisoncor.gui.panel.PanelImage();
        alterar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        date_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mod_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cor_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        docVisitante_txt = new javax.swing.JTextField();
        tip_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nomeVisitante_txt = new javax.swing.JTextField();
        num_txt = new javax.swing.JTextField();
        status1_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        time_txt = new javax.swing.JTextField();
        pla200_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 92, 143));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tech Solutions S.A");

        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage7Layout = new javax.swing.GroupLayout(panelImage7);
        panelImage7.setLayout(panelImage7Layout);
        panelImage7Layout.setHorizontalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        panelImage7Layout.setVerticalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        sair_btn2.setBackground(new java.awt.Color(255, 51, 51));
        sair_btn2.setText("X");
        sair_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btn2ActionPerformed(evt);
            }
        });

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/casa.png"))); // NOI18N
        panelImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(sair_btn2)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sair_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 740, 100);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel7.setText("CONSULTAR ESTACIONAMENTO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 110, 429, 38);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Tela de consulta dos carros cadastrados no estacionamento");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 380, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Estacionamento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 160, 140, 30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, carrosList, tabela1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${carroId}"));
        columnBinding.setColumnName("Carro Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliPlaca}"));
        columnBinding.setColumnName("Cli Placa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliModelo}"));
        columnBinding.setColumnName("Cli Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliCor}"));
        columnBinding.setColumnName("Cli Cor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliTipo}"));
        columnBinding.setColumnName("Cli Tipo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliNumero}"));
        columnBinding.setColumnName("Cli Numero");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${visitanteId}"));
        columnBinding.setColumnName("Visitante Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliStatus}"));
        columnBinding.setColumnName("Cli Status");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(tabela1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 730, 90);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Digite a placa para realizar a pesquisa:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 310, 260, 17);
        jPanel1.add(cod8_txt);
        cod8_txt.setBounds(600, 310, 90, 30);

        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lupa.png"))); // NOI18N
        pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pesquisarLayout = new javax.swing.GroupLayout(pesquisar);
        pesquisar.setLayout(pesquisarLayout);
        pesquisarLayout.setHorizontalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pesquisarLayout.setVerticalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(pesquisar);
        pesquisar.setBounds(700, 310, 20, 20);

        alterar.setBackground(new java.awt.Color(0, 92, 143));
        alterar.setForeground(new java.awt.Color(255, 255, 255));
        alterar.setText("ALTERAR");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        jPanel1.add(alterar);
        alterar.setBounds(590, 350, 110, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Data:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 310, 50, 19);

        date_txt.setEditable(false);
        jPanel1.add(date_txt);
        date_txt.setBounds(80, 310, 100, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Modelo:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 440, 80, 19);
        jPanel1.add(mod_txt);
        mod_txt.setBounds(140, 440, 210, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Nome do Visitante:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 440, 140, 19);
        jPanel1.add(cor_txt);
        cor_txt.setBounds(140, 480, 210, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Status:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 520, 120, 19);

        docVisitante_txt.setEditable(false);
        jPanel1.add(docVisitante_txt);
        docVisitante_txt.setBounds(510, 480, 210, 30);
        jPanel1.add(tip_txt);
        tip_txt.setBounds(140, 520, 210, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Tipo de vaga:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 520, 100, 19);

        nomeVisitante_txt.setEditable(false);
        nomeVisitante_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeVisitante_txtActionPerformed(evt);
            }
        });
        jPanel1.add(nomeVisitante_txt);
        nomeVisitante_txt.setBounds(510, 440, 210, 30);
        jPanel1.add(num_txt);
        num_txt.setBounds(510, 400, 210, 30);

        status1_txt.setEditable(false);
        status1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1_txtActionPerformed(evt);
            }
        });
        jPanel1.add(status1_txt);
        status1_txt.setBounds(510, 520, 210, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Cor:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 480, 100, 19);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Número da vaga:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 400, 120, 19);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Documento:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(370, 480, 120, 19);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Hora:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 350, 50, 19);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Placa:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(30, 400, 50, 19);

        time_txt.setEditable(false);
        jPanel1.add(time_txt);
        time_txt.setBounds(80, 350, 100, 30);
        jPanel1.add(pla200_txt);
        pla200_txt.setBounds(140, 400, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(733, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sair_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btn2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btn2ActionPerformed

    private void panelImage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage3MouseClicked
       new Menu_GUI(Login_DAO.tipoUsuarioLogado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelImage3MouseClicked

    private void pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseClicked
        Controller.Carro_DAO.consultar();
        refresh();
    }//GEN-LAST:event_pesquisarMouseClicked

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        Controller.Carro_DAO.alterar();
        refresh();
    }//GEN-LAST:event_alterarActionPerformed

    private void nomeVisitante_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeVisitante_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeVisitante_txtActionPerformed

    private void status1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status1_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaEst_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private java.util.List<View.Carros> carrosList;
    private javax.persistence.Query carrosQuery;
    public static javax.swing.JTextField cod8_txt;
    public static javax.swing.JTextField cor_txt;
    public static javax.swing.JTextField date_txt;
    public static javax.swing.JTextField docVisitante_txt;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<View.Func> funcList;
    private javax.persistence.Query funcQuery;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField mod_txt;
    public static javax.swing.JTextField nomeVisitante_txt;
    public static javax.swing.JTextField num_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelImage pesquisar;
    public static javax.swing.JTextField pla200_txt;
    private javax.swing.JButton sair_btn2;
    public static javax.swing.JTextField status1_txt;
    private javax.swing.JTable tabela1;
    public static javax.swing.JTextField time_txt;
    public static javax.swing.JTextField tip_txt;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
